version: '3.8'


services:
  mysql:
    ports:
      - "3306:3306"
    command: >
    volumes:
      - ./logs/mysql:/var/log/mysql

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Information
    volumes:
      - ./RegistroEstudiantes.API:/app:ro
      - ./logs/api:/app/logs
    develop:
      watch:
        - action: rebuild
          path: ./RegistroEstudiantes.API
          target: /app

  frontend:
    volumes:
      - ./logs/nginx:/var/log/nginx
    develop:
      watch:
        - action: rebuild
          path: ./RegistroEstudiantes.Web/src
          target: /usr/share/nginx/html

  phpmyadmin:
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=http://localhost:8080/
